### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by murphyk** [probml/JSL#2]
- [x] need to explain that C in  [lds.kalman_step](https://github.com/probml/JSL/blob/main/scripts/linreg_kf_demo.py) can be a constant matrix or a function of time, as in [this linreg example](https://github.com/probml/JSL/blob/main/scripts/linreg_kf_demo.py#L38)
- [x] it would be clearer to [rename xt ](https://github.com/probml/JSL/blob/main/scripts/linreg_kf_demo.py#L38)to `obs` or `observed`
- [x] you say `x, y = xt` [in this KF code](https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter.py#L324).  What does this mean? What is y?
- [x] you say `xt, obs.= xs` [in this EKF code](https://github.com/probml/JSL/blob/main/jsl/nlds/extended_kalman_filter.py#L42). I think this should be `obs, inputs = xs`. Need to explain signature of fx and fz!

**Comment by gerdm** [comment]
Fixed in latest push
