### ISSUE TITLE
Status of this companion library

### ISSUE THREAD

**Issue by AdrienCorenflos** [probml/JSL#20]
Hi,
 
I was just having a look at this. What is the status and scope of this code? It is not working at the moment (bad imports) and has no test? I was keen to have a look at implementing the parallel-in-time versions of Kalman (linear + non-linear) and HMM (inference + Viterbi) as I have them roughly ready in a few places, but I'd prefer to know if it's worth the effort :D

Adrien

**Comment by karalleyna** [comment]
Hi Adrien,

I can run the demos on my computer. Could you run a script like `python3 -m jsl.demos.<script-name>`? Btw, hmm code was tested and it was also approved by [distrax](https://github.com/deepmind/distrax/blob/master/distrax/_src/utils/hmm.py) team. If there are any other problems or questions, please let us know :)

**Comment by murphyk** [comment]
Hi @AdrienCorenflos . This library is a mix of stuff that we believe/hope is stable (eg hmm, lds, nlds, demos), and some experimental stuff (seql, foo_vb). I will move the latter into an `experimental` folder to make it clearer. 

What issues did you have with the core code? We can create GSOC projects to clean up the code, if you want to suggest some things.

We don't have any parallel in time inference code. I think you can find that at https://github.com/AaltoML/kalman-jax and https://github.com/AaltoML/BayesNewton/, although these libraries seem to focus on SSMs derived from GPs.
