### ISSUE TITLE
replace  jax.ops.index_update with jax.numpy.at in all JSL code

### ISSUE THREAD

**Issue by murphyk** [probml/JSL#25]
jax.ops.index_update has been removed (see https://github.com/google/jax/commit/f51a05a889f2fcb19946352b9d65f2b6c49fec4a) which breaks some JSL code.
Please use  [jnp.at()](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html) instead.

**Comment by murphyk** [comment]
Example of the problem:
<img width="800" alt="Screen Shot 2022-03-23 at 12 17 38 PM" src="https://user-images.githubusercontent.com/4632336/159778837-8d8c0439-e90b-465c-bb6c-04cb79561033.png">

**Comment by karalleyna** [comment]
Done.
