### ISSUE TITLE
refactor ekf_vs_ukf_mlp.py into ekf_mlp_demo and ukf_mlp_demo

### ISSUE THREAD

**Issue by murphyk** [probml/JSL#33]
Separate out ekf and ukf from 
https://github.com/probml/JSL/blob/main/jsl/demos/ekf_vs_ukf_mlp.py
See also https://github.com/probml/JSL/issues/30

**Comment by karalleyna** [comment]
- [EKF demo](https://github.com/probml/JSL/blob/main/jsl/demos/ekf_mlp.py)
- [UKF demo](https://github.com/probml/JSL/blob/main/jsl/demos/ukf_mlp.py)
