### ISSUE TITLE
remove path munging

### ISSUE THREAD

**Issue by murphyk** [probml/JSL#53]
https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter_test.py#L3

```
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
```
is bad style. Why is it needed?

**Comment by gileshd** [comment]
Yeah my bad sorry not necessary! Forgot to remove it after fiddling around with some testing stuff locally.

I'll make a PR to get rid of it and make the import use the absolute path.
